[package]
name = "rfw-ebpf"
version = "0.1.7"
edition.workspace = true

[dependencies]
rfw-common = { path = "../rfw-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "rfw"
path = "src/main.rs"
